controller_list:
  - name: fake_gripper_right_controller
    joints:
      - arm_joint_5
      - gripper_finger_joint_r
  - name: fake_gripper_left_controller
    joints:
      - arm_joint_5
      - gripper_finger_joint_l
  - name: fake_youbot_arm_controller
    joints:
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
  - name: fake_base_controller
    joints:
      - arm_joint_1
      - arm_joint_2